### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by joetm** [aalto-ui/aim#1]
Some of the metrics are hard to understand.
For each metric, it should be indicated if a high value is good or bad.

**Comment by mplaine** [comment]
> The Backend config file for production points to an empty page.

This issue has been fixed now. Thanks for letting us know!

**Comment by mplaine** [comment]
> Some of the metrics are hard to understand.
> For each metric, it should be indicated if a high value is good or bad.

We are aware of this issue and have plans to improve the representation of the results.

**Comment by mplaine** [comment]
@joetm The latest version of AIM (commit `9d064c4f746028defacff165b9c3e5167197afd3`) includes a summary view section and textual descriptions next to metric scores to ease the interpretation of metric results.
