### ISSUE TITLE
AIM2 metrics integration

### ISSUE THREAD

**Issue by havanakoda** [aalto-ui/aim#10]
Hi,

Is it possible to launch the backend server with the AIM2 metrics?

**Comment by mplaine** [comment]
The backend server and the old metrics are implemented in Python 2. The new AIM2 metrics are implemented in Python 3.

The plan is to first revise and update all the old metrics, after which we will update the backend server to be compatible with them and Python 3.

**Comment by mplaine** [comment]
Please, see the "aim2" branch which as of now includes a refactored codebase (incl. the web application) and the AIM2 metrics published earlier last year.
