### ISSUE TITLE
Error message in dev environment

### ISSUE THREAD

**Issue by havanakoda** [aalto-ui/aim#2]
Hi,

I installed it locally and everything works (great job, compliments!!) 
However, I had to comment the first two lines of the file 'requirements.txt' and install the package python-tk that was not indicated in the docs.

Finally, when I launch the front-end with 'npm run dev',  I get this error message:

`(node:12977) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/xx/aim/aim_frontend/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:12977) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mplaine** [comment]
> I installed it locally and everything works (great job, compliments!!)
> However, I had to comment the first two lines of the file 'requirements.txt' and install the package python-tk that was not indicated in the docs.

Can you post the error message you got before commenting the first two lines of the 'requirements.txt' file.

> Finally, when I launch the front-end with 'npm run dev', I get this error message:
> 
> `(node:12977) UnhandledPromiseRejectionWarning: Error: Exited with code 3 at ChildProcess.cp.once.code (/home/xx/aim/aim_frontend/node_modules/opn/index.js:84:13) at Object.onceWrapper (events.js:273:13) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Socket.stream.socket.on (internal/child_process.js:381:11) at Socket.emit (events.js:182:13) at Pipe._handle.close (net.js:606:12) (node:12977) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) (node:12977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Which version of Node.js and npm you have on your computer?

**Comment by mplaine** [comment]
I managed to successfully install AIM on another computer running OS X 10.11.6. The computer has the following software:
* Python 2.7.15
* pip 18.1
* Node 8.9.1
* npm 5.5.1

Also, I didn't need to edit `requirements.txt` at all, and `npm run dev` ran without errors.

Hope this helps!
+Markku

**Comment by havanakoda** [comment]
Hi, the message I got before commenting the first two lines was:

`  Could not find a version that satisfies the requirement aim-metrics==1.0.2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for aim-metrics==1.0.2 (from -r requirements.txt (line 1))`

My computer runs Ubuntu 18.04 with the following software:

- Python 2.7.15
- pip 9.0.1
- Node 10.12.0
- npm 6.4.1

Everything works, but I got such error message in dev mode.

**Comment by mplaine** [comment]
> Everything works, but I got such error message in dev mode.

`UnhandledPromiseRejectionWarning` is raised probably because the dev server tries to open the application in a browser window.
