### ISSUE TITLE
Typo in Balance formula

### ISSUE THREAD

**Issue by m4hmoud** [aalto-ui/aim#8]
https://github.com/aalto-ui/aim/blob/9d064c4f746028defacff165b9c3e5167197afd3/aim_metrics/aim_metrics/perceptual_fluency/pf6_quadtree_decomposition.py#L130

The denominator should be `max(abs(w_left), abs(w_right))`.

**Comment by mplaine** [comment]
Fixed the typo. Thank you for your contribution!
