### ISSUE TITLE
PNGs

### ISSUE THREAD

**Issue by Tapestes** [aalto-ui/aim#84]
Trying to use AIM to evaluate a .png created from this pdf: https://aeronav.faa.gov/d-tpp/2303/00380IL1.PDF.  I'm getting "Whoops! We are having some problems with your input. Please refresh the page and try again with a different URL or image."  I tried several other .pngs, including a screenshot of the google homepage, but no joy.  If it matters, I'm on Mac running Silicon.  Thanks much.

**Comment by mplaine** [comment]
![aim_minimum_size](https://user-images.githubusercontent.com/1519259/233111627-68158d21-6af7-451b-8686-e0bb6c03578e.png)

According to error logs "Image is too small (min 1280 x 800 pixels): 1207 x 1159 pixels"

Could you try again with an input image that meets the minimum size criteria of 1280 x 800 pixels?

**Comment by Tapestes** [comment]
That's the trick.  Thanks.
